# Generated by Django 2.2.3 on 2019-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0002_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='defaultthumb.jpg', upload_to='thunbnail_pics'),
        ),
    ]
